"""upgrade

Revision ID: 358c2a2ad99b
Revises: d077bf4ffc35
Create Date: 2024-08-22 12:46:38.364264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '358c2a2ad99b'
down_revision: Union[str, None] = 'd077bf4ffc35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name', new_column_name='role_name')
    # ### end Alembic commands ###
