"""userModel change

Revision ID: d077bf4ffc35
Revises: 
Create Date: 2024-08-22 12:40:11.521626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd077bf4ffc35'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'id', new_column_name='role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
